//go:build linux

// Package services installs file-manager context-menu entries that launch
// PGP Manager with "--context <action> <path>..." arguments. macOS needs no
// installation (NSServices from Info.plist); on Windows the entries live in
// the per-user registry, on Linux in the user's file-manager config dirs.
package services

import (
	"fmt"
	"os"
	"path/filepath"
)

var menuEntries = []struct{ name, title, action string }{
	{"encrypt", "Encrypt", "encrypt-file"},
	{"decrypt", "Decrypt", "decrypt-file"},
	{"sign", "Sign", "sign-file"},
	{"verify", "Verify Signature", "verify-file"},
}

func dataHome() (string, error) {
	if xdg := os.Getenv("XDG_DATA_HOME"); xdg != "" {
		return xdg, nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".local", "share"), nil
}

// nautilusScriptsDir is a submenu directory below Nautilus' "Scripts" menu.
func nautilusScriptsDir(data string) string {
	return filepath.Join(data, "nautilus", "scripts", "PGP Manager")
}

func kioServiceMenuPath(data string) string {
	return filepath.Join(data, "kio", "servicemenus", "pgp-manager.desktop")
}

func nemoActionPath(data, name string) string {
	return filepath.Join(data, "nemo", "actions", "pgp-manager-"+name+".nemo_action")
}

// Supported reports whether context-menu installation applies to this OS.
func Supported() bool { return true }

// Installed reports whether context-menu entries exist for at least one
// file manager.
func Installed() bool {
	data, err := dataHome()
	if err != nil {
		return false
	}
	if _, err := os.Stat(nautilusScriptsDir(data)); err == nil {
		return true
	}
	if _, err := os.Stat(kioServiceMenuPath(data)); err == nil {
		return true
	}
	for _, e := range menuEntries {
		if _, err := os.Stat(nemoActionPath(data, e.name)); err == nil {
			return true
		}
	}
	return false
}

// Install writes context-menu entries for Nautilus (GNOME), Dolphin (KDE),
// and Nemo (Cinnamon), all pointing at the currently running executable.
// File managers pick the files up without a restart (Nautilus may need one).
func Install() error {
	exe, err := os.Executable()
	if err != nil {
		return fmt.Errorf("services: %w", err)
	}
	if resolved, err := filepath.EvalSymlinks(exe); err == nil {
		exe = resolved
	}
	data, err := dataHome()
	if err != nil {
		return fmt.Errorf("services: %w", err)
	}

	if err := installNautilus(data, exe); err != nil {
		return err
	}
	if err := installKio(data, exe); err != nil {
		return err
	}
	return installNemo(data, exe)
}

func installNautilus(data, exe string) error {
	dir := nautilusScriptsDir(data)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("services: nautilus: %w", err)
	}
	for _, e := range menuEntries {
		// Nautilus passes the selection newline-separated in an env var;
		// IFS splitting keeps paths with spaces intact (newlines in file
		// names are not supported).
		script := fmt.Sprintf(`#!/bin/sh
# Generated by PGP Manager — safe to delete.
IFS='
'
set -f
set -- $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
[ "$#" -gt 0 ] || exit 0
exec "%s" --context %s "$@"
`, exe, e.action)
		path := filepath.Join(dir, e.title)
		if err := os.WriteFile(path, []byte(script), 0755); err != nil {
			return fmt.Errorf("services: nautilus: %w", err)
		}
	}
	return nil
}

func installKio(data, exe string) error {
	path := kioServiceMenuPath(data)
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("services: kio: %w", err)
	}
	entry := `[Desktop Entry]
Type=Service
MimeType=all/allfiles;
X-KDE-ServiceTypes=KonqPopupMenu/Plugin
X-KDE-Submenu=PGP Manager
Actions=pgpEncrypt;pgpDecrypt;pgpSign;pgpVerify;
`
	actionIDs := map[string]string{
		"encrypt": "pgpEncrypt", "decrypt": "pgpDecrypt",
		"sign": "pgpSign", "verify": "pgpVerify",
	}
	for _, e := range menuEntries {
		entry += fmt.Sprintf(`
[Desktop Action %s]
Name=%s
Exec="%s" --context %s %%F
`, actionIDs[e.name], e.title, exe, e.action)
	}
	// KIO requires servicemenus to be executable since KDE Frameworks 5.85.
	if err := os.WriteFile(path, []byte(entry), 0755); err != nil {
		return fmt.Errorf("services: kio: %w", err)
	}
	return nil
}

func installNemo(data, exe string) error {
	dir := filepath.Join(data, "nemo", "actions")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("services: nemo: %w", err)
	}
	for _, e := range menuEntries {
		action := fmt.Sprintf(`[Nemo Action]
Name=PGP: %s
Comment=%s the selected files with PGP Manager
Exec="%s" --context %s %%F
Selection=any
Extensions=any;
`, e.title, e.title, exe, e.action)
		if err := os.WriteFile(nemoActionPath(data, e.name), []byte(action), 0644); err != nil {
			return fmt.Errorf("services: nemo: %w", err)
		}
	}
	return nil
}

// Uninstall removes all context-menu entries written by Install.
func Uninstall() error {
	data, err := dataHome()
	if err != nil {
		return fmt.Errorf("services: %w", err)
	}
	if err := os.RemoveAll(nautilusScriptsDir(data)); err != nil {
		return fmt.Errorf("services: nautilus: %w", err)
	}
	if err := os.Remove(kioServiceMenuPath(data)); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("services: kio: %w", err)
	}
	for _, e := range menuEntries {
		if err := os.Remove(nemoActionPath(data, e.name)); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("services: nemo: %w", err)
		}
	}
	return nil
}
