// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AddCustomKeyserver(arg1:string):Promise<void>;

export function AddSubkey(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AppVersion():Promise<string>;

export function AutostartSupported():Promise<boolean>;

export function CachePassphrase(arg1:string,arg2:string):Promise<void>;

export function ConfirmSetup(arg1:string):Promise<void>;

export function ContextMenuInstalled():Promise<boolean>;

export function ContextMenuSupported():Promise<boolean>;

export function DecryptFile(arg1:string,arg2:string,arg3:string):Promise<model.FileResult>;

export function DecryptFileWithOutput(arg1:string,arg2:string,arg3:string,arg4:string):Promise<model.FileResult>;

export function DecryptText(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<model.DecryptResult>;

export function DefaultConfigDir():Promise<string>;

export function DeleteKey(arg1:string):Promise<void>;

export function EncryptFile(arg1:string,arg2:Array<string>,arg3:string):Promise<model.FileResult>;

export function EncryptFileWithOutput(arg1:string,arg2:Array<string>,arg3:string,arg4:string):Promise<model.FileResult>;

export function EncryptText(arg1:string,arg2:Array<string>,arg3:string,arg4:string):Promise<model.EncryptResult>;

export function ExportKey(arg1:string):Promise<string>;

export function ExportKeyToFile(arg1:string):Promise<void>;

export function FindDecryptionKey(arg1:string):Promise<string>;

export function FindDecryptionKeyFromFile(arg1:string):Promise<string>;

export function FrontendReady():Promise<void>;

export function GenerateKey(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function GetAutostart():Promise<boolean>;

export function GetAvailableUpdate():Promise<string>;

export function GetCachedPassphrase(arg1:string):Promise<string>;

export function GetConfig():Promise<model.AppConfig>;

export function GetPlatform():Promise<string>;

export function GetPublicKey(arg1:string):Promise<string>;

export function HasCachedPassphrase(arg1:string):Promise<boolean>;

export function ImportFromKeyserver(arg1:string,arg2:string):Promise<void>;

export function ImportKey(arg1:string):Promise<void>;

export function ImportMultipleKeys(arg1:string):Promise<model.MultiImportResult>;

export function ImportPrivateKey(arg1:string,arg2:string):Promise<void>;

export function InstallApp():Promise<void>;

export function InstallContextMenu():Promise<void>;

export function InstallSupported():Promise<boolean>;

export function IsInstalled():Promise<boolean>;

export function ListKeys():Promise<Array<model.KeyInfo>>;

export function ListKeyservers():Promise<Array<model.KeyserverEntry>>;

export function NeedsSetup():Promise<boolean>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenFileDialog():Promise<string>;

export function OpenFolder(arg1:string):Promise<void>;

export function PreviewKeys(arg1:string):Promise<Array<model.KeyInfo>>;

export function PublishToKeyserver(arg1:string,arg2:string):Promise<void>;

export function ReadClipboard():Promise<string>;

export function RemoveCustomKeyserver(arg1:string):Promise<void>;

export function RevokeSubkey(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveConfig(arg1:model.AppConfig):Promise<void>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function SetClipboardText(arg1:string):Promise<void>;

export function SignText(arg1:string,arg2:string,arg3:string):Promise<model.SignResult>;

export function StartKeyserverSearch(arg1:string,arg2:string):Promise<void>;

export function UninstallContextMenu():Promise<void>;

export function VerifyText(arg1:string):Promise<model.VerifyResult>;

export function WindowClose():Promise<void>;

export function WindowMaximise():Promise<void>;

export function WindowMinimise():Promise<void>;
