// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomKeyserver(arg1) {
  return window['go']['main']['App']['AddCustomKeyserver'](arg1);
}

export function AddSubkey(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddSubkey'](arg1, arg2, arg3, arg4);
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function AutostartSupported() {
  return window['go']['main']['App']['AutostartSupported']();
}

export function CachePassphrase(arg1, arg2) {
  return window['go']['main']['App']['CachePassphrase'](arg1, arg2);
}

export function ConfirmSetup(arg1) {
  return window['go']['main']['App']['ConfirmSetup'](arg1);
}

export function DecryptFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DecryptFile'](arg1, arg2, arg3);
}

export function DecryptFileWithOutput(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DecryptFileWithOutput'](arg1, arg2, arg3, arg4);
}

export function DecryptText(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DecryptText'](arg1, arg2, arg3, arg4);
}

export function DefaultConfigDir() {
  return window['go']['main']['App']['DefaultConfigDir']();
}

export function DeleteKey(arg1) {
  return window['go']['main']['App']['DeleteKey'](arg1);
}

export function EncryptFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['EncryptFile'](arg1, arg2, arg3);
}

export function EncryptFileWithOutput(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EncryptFileWithOutput'](arg1, arg2, arg3, arg4);
}

export function EncryptText(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EncryptText'](arg1, arg2, arg3, arg4);
}

export function ExportKey(arg1) {
  return window['go']['main']['App']['ExportKey'](arg1);
}

export function ExportKeyToFile(arg1) {
  return window['go']['main']['App']['ExportKeyToFile'](arg1);
}

export function FindDecryptionKey(arg1) {
  return window['go']['main']['App']['FindDecryptionKey'](arg1);
}

export function FindDecryptionKeyFromFile(arg1) {
  return window['go']['main']['App']['FindDecryptionKeyFromFile'](arg1);
}

export function GenerateKey(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GenerateKey'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAutostart() {
  return window['go']['main']['App']['GetAutostart']();
}

export function GetAvailableUpdate() {
  return window['go']['main']['App']['GetAvailableUpdate']();
}

export function GetCachedPassphrase(arg1) {
  return window['go']['main']['App']['GetCachedPassphrase'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetPublicKey(arg1) {
  return window['go']['main']['App']['GetPublicKey'](arg1);
}

export function HasCachedPassphrase(arg1) {
  return window['go']['main']['App']['HasCachedPassphrase'](arg1);
}

export function ImportFromKeyserver(arg1, arg2) {
  return window['go']['main']['App']['ImportFromKeyserver'](arg1, arg2);
}

export function ImportKey(arg1) {
  return window['go']['main']['App']['ImportKey'](arg1);
}

export function ImportMultipleKeys(arg1) {
  return window['go']['main']['App']['ImportMultipleKeys'](arg1);
}

export function ImportPrivateKey(arg1, arg2) {
  return window['go']['main']['App']['ImportPrivateKey'](arg1, arg2);
}

export function InstallApp() {
  return window['go']['main']['App']['InstallApp']();
}

export function InstallSupported() {
  return window['go']['main']['App']['InstallSupported']();
}

export function IsInstalled() {
  return window['go']['main']['App']['IsInstalled']();
}

export function ListKeys() {
  return window['go']['main']['App']['ListKeys']();
}

export function ListKeyservers() {
  return window['go']['main']['App']['ListKeyservers']();
}

export function NeedsSetup() {
  return window['go']['main']['App']['NeedsSetup']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function PreviewKeys(arg1) {
  return window['go']['main']['App']['PreviewKeys'](arg1);
}

export function PublishToKeyserver(arg1, arg2) {
  return window['go']['main']['App']['PublishToKeyserver'](arg1, arg2);
}

export function ReadClipboard() {
  return window['go']['main']['App']['ReadClipboard']();
}

export function RemoveCustomKeyserver(arg1) {
  return window['go']['main']['App']['RemoveCustomKeyserver'](arg1);
}

export function RevokeSubkey(arg1, arg2, arg3) {
  return window['go']['main']['App']['RevokeSubkey'](arg1, arg2, arg3);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function SetClipboardText(arg1) {
  return window['go']['main']['App']['SetClipboardText'](arg1);
}

export function SignText(arg1, arg2, arg3) {
  return window['go']['main']['App']['SignText'](arg1, arg2, arg3);
}

export function StartKeyserverSearch(arg1, arg2) {
  return window['go']['main']['App']['StartKeyserverSearch'](arg1, arg2);
}

export function VerifyText(arg1) {
  return window['go']['main']['App']['VerifyText'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMaximise() {
  return window['go']['main']['App']['WindowMaximise']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}
